
envIDs  = { "airraid"   : "AirRaid-v0",
            "alien"     : "Alien-v0",
            "amidar"    : "Amidar-v0",
            "assault"   : "Assault-v0",
            "asterix"   : "Asterix-v0",
            "asteroids" : "Asteroids-v0",
            "atlantis"  : "Atlantis-v0",
            "bankheist" : "BankHeist-v0",
            "battlezone": "BattleZone-v0",
            "beamrider" : "BeamRider-v0",
            "berzerk"   : "Berzerk-v0",
            "bowling"   : "Bowling-v0",
            "boxing"    : "Boxing-v0",
            "breakout"  : "Breakout-v0",
            "carnival"  : "Carnival-v0",
            "centipede" : "Centipede-v0",
            "choppercommand": "ChopperCommand-v0",
            "crazyclimber": "CrazyClimber-v0",
            "demoattack": "DemoAttack-v0",
            "doubledunk": "DoubleDunk-v0",
            "elevatoraction": "ElevatorAction-v0",
            "enduro"    : "Enduro-v0",
            "fishingderby": "FishingDerby-v0",
            "freeway"   : "Freeway-v0",
            "frostbite" : "Frostbite-v0",
            "gopher"    : "Gopher-v0",
            "gravitar"  : "Gravitar-v0",
            "icehockey" : "IceHockey-v0",
            "jamesbond" : "Jamesbond-v0",
            "journeyescape": "JourneyEscape-v0",
            "kangaroo"  : "Kangaroo-v0",
            "krull"     : "Krull-v0",
            "kungfumaster": "KungFuMaster-v0",
            "montezumarevenge": "MontezumaRevenge-v0",
            "pacman"    : "MsPacman-v0",
            "namethisgame": "NameThisGame-v0",
            "phoenix"   : "Phoenix-v0",
            "pitfall"   : "Pitfall-v0",
            "pong"      : "Pong-v0",
            "pooyan"    : "Pooyan-v0",
            "privateeye": "PrivateEye-v0",
            "qbert"     : "Qbert-v0",
            "riverraid" : "Riverraid-v0",
            "roadrunner": "Roadrunner-v0",
            "robotank"  : "Robotank-v0",
            "seaquest"  : "Seaquest-v0",
            "skiing"    : "Skiing-v0",
            "solaris"   : "Solaris-v0",
            "spaceinvaders": "SpaceInvaders-v0",
            "stargunner": "StarGunner-v0",
            "tennis"    : "Tennis-v0",
            "timepilot" : "TimePilot-v0",
            "tutankham" : "Tutankham-v0",
            "upndown"   : "UpNDown-v0",
            "venture"   : "Venture-v0",
            "pinball"   : "VideoPinball-v0",
            "wizardofwor": "WizardOfWor-v0",
            "yarsRevenge": "YarsRevenge-v0",
            "zaxxon"    : "Zaxxon-v0"}

