
envIDs  = { "airraid"   : "AirRaidNoFrameskip-v4",
            "alien"     : "AlienNoFrameskip-v4",
            "amidar"    : "AmidarNoFrameskip-v4",
            "assault"   : "AssaultNoFrameskip-v4",
            "asterix"   : "AsterixNoFrameskip-v4",
            "asteroids" : "AsteroidsNoFrameskip-v4",
            "atlantis"  : "AtlantisNoFrameskip-v4",
            "bankheist" : "BankHeistNoFrameskip-v4",
            "battlezone": "BattleZoneNoFrameskip-v4",
            "beamrider" : "BeamRiderNoFrameskip-v4",
            "berzerk"   : "BerzerkNoFrameskip-v4",
            "bowling"   : "BowlingNoFrameskip-v4",
            "boxing"    : "BoxingNoFrameskip-v4",
            "breakout"  : "BreakoutNoFrameskip-v4",
            "carnival"  : "CarnivalNoFrameskip-v4",
            "centipede" : "CentipedeNoFrameskip-v4",
            "choppercommand": "ChopperCommandNoFrameskip-v4",
            "crazyclimber": "CrazyClimberNoFrameskip-v4",
            "demoattack": "DemoAttackNoFrameskip-v4",
            "doubledunk": "DoubleDunkNoFrameskip-v4",
            "elevatoraction": "ElevatorActionNoFrameskip-v4",
            "enduro"    : "EnduroNoFrameskip-v4",
            "fishingderby": "FishingDerbyNoFrameskip-v4",
            "freeway"   : "FreewayNoFrameskip-v4",
            "frostbite" : "FrostbiteNoFrameskip-v4",
            "gopher"    : "GopherNoFrameskip-v4",
            "gravitar"  : "GravitarNoFrameskip-v4",
            "icehockey" : "IceHockeyNoFrameskip-v4",
            "jamesbond" : "JamesbondNoFrameskip-v4",
            "journeyescape": "JourneyEscapeNoFrameskip-v4",
            "kangaroo"  : "KangarooNoFrameskip-v4",
            "krull"     : "KrullNoFrameskip-v4",
            "kungfumaster": "KungFuMasterNoFrameskip-v4",
            "montezumarevenge": "MontezumaRevengeNoFrameskip-v4",
            "pacman"    : "MsPacmanNoFrameskip-v4",
            "namethisgame": "NameThisGameNoFrameskip-v4",
            "phoenix"   : "PhoenixNoFrameskip-v4",
            "pitfall"   : "PitfallNoFrameskip-v4",
            "pong"      : "PongNoFrameskip-v4",
            "pooyan"    : "PooyanNoFrameskip-v4",
            "privateeye": "PrivateEyeNoFrameskip-v4",
            "qbert"     : "QbertNoFrameskip-v4",
            "riverraid" : "RiverraidNoFrameskip-v4",
            "roadrunner": "RoadrunnerNoFrameskip-v4",
            "robotank"  : "RobotankNoFrameskip-v4",
            "seaquest"  : "SeaquestNoFrameskip-v4",
            "skiing"    : "SkiingNoFrameskip-v4",
            "solaris"   : "SolarisNoFrameskip-v4",
            "spaceinvaders": "SpaceInvadersNoFrameskip-v4",
            "stargunner": "StarGunnerNoFrameskip-v4",
            "tennis"    : "TennisNoFrameskip-v4",
            "timepilot" : "TimePilotNoFrameskip-v4",
            "tutankham" : "TutankhamNoFrameskip-v4",
            "upndown"   : "UpNDownNoFrameskip-v4",
            "venture"   : "VentureNoFrameskip-v4",
            "pinball"   : "VideoPinballNoFrameskip-v4",
            "wizardofwor": "WizardOfWorNoFrameskip-v4",
            "yarsRevenge": "YarsRevengeNoFrameskip-v4",
            "zaxxon"    : "ZaxxonNoFrameskip-v4"}

